[package]
name = "NSCool"
version = "0.1.0"
authors = ["axect <edeftg@gmail.com>"]
edition = "2018"

[dependencies]
natural_unit = "0.1"
inline-python = "0.3"
rayon = "1"

[dependencies.peroxide]
version = "0.16"
features = ["oxidize", "plot"]